
package com.dsx.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.dsx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.dsx.service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "finUserById", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.FinUserById")
    @ResponseWrapper(localName = "finUserByIdResponse", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.FinUserByIdResponse")
    public User finUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveUser", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.SaveUser")
    @ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.SaveUserResponse")
    public void saveUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.dsx.service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.FindAllUsers")
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.FindAllUsersResponse")
    public List<User> findAllUsers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://service.dsx.com/", className = "com.dsx.service.UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
